In [2]:
import numpy as np

1D array using np.array

In [4]:
np.array([1,2,3])

array([1, 2, 3])

2D array using np.array

In [5]:
np.array([[1,2,3],[4,6,7]])

array([[1, 2, 3],
       [4, 6, 7]])

3D array using np.array

In [6]:
np.array([[[1,2],[3,4]],[[3,6],[4,6]]])

array([[[1, 2],
        [3, 4]],

       [[3, 6],
        [4, 6]]])

Creating arrays with a specific data type:  using dtype

In [7]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [8]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

np.arange() 

In [9]:
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

np.reshape()

In [11]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

np.ones() and np.zeros()  Pass shape as a tuple

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

np.random.random()

In [14]:
np.random.random((2,3))

array([[0.51353895, 0.67074481, 0.60259198],
       [0.98917743, 0.84848569, 0.38289976]])

np.linspace() 

In [15]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

np.identity()

In [16]:
a1=np.identity(3)
print(a1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


3. Array Attributes

1. ndim

In [17]:
b1=a1.ndim
print(b1)

2


In [18]:
a1.shape

(3, 3)

In [19]:
a1.size

9

In [20]:
a1.itemsize

8

In [21]:
a1.dtype

dtype('float64')